"""add conditional dependency fields to requirements

Revision ID: 55043a505448
Revises: 95d8a36e4822
Create Date: 2026-08-01 01:39:32.143438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55043a505448'
down_revision: Union[str, Sequence[str], None] = '95d8a36e4822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('depends_on_requirement_id', sa.Integer(), nullable=True))
    op.add_column('requirements', sa.Column('depends_on_values', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'requirements', 'requirements', ['depends_on_requirement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_column('requirements', 'depends_on_values')
    op.drop_column('requirements', 'depends_on_requirement_id')
    # ### end Alembic commands ###
