"""add validation_type to requirements

Revision ID: 95d8a36e4822
Revises: c8d24b57b173
Create Date: 2026-08-01 01:02:26.220886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d8a36e4822'
down_revision: Union[str, Sequence[str], None] = 'c8d24b57b173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('validation_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'validation_type')
    # ### end Alembic commands ###
