"""add french translation fields to service, requirement, and step

Revision ID: fc707795d987
Revises: 55043a505448
Create Date: 2026-08-01 02:08:05.328479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc707795d987'
down_revision: Union[str, Sequence[str], None] = '55043a505448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('name_fr', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('name_fr', sa.String(length=255), nullable=True))
    op.add_column('steps', sa.Column('instruction_fr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'instruction_fr')
    op.drop_column('services', 'name_fr')
    op.drop_column('requirements', 'name_fr')
    # ### end Alembic commands ###
